---
- name: Remove cv_configlet_v3
  hosts: cvp
  connection: local
  gather_facts: no
  vars:
    configlet_list:
      Ansible_Demo_Configlet: "! This is a Ansible Demo Configlet\n!"
      SNMP_Enable_Configlet: "{{ lookup('file', 'templates/snmp_enable_configlet.txt') }}"
  tasks:
    - name: 'Remove configlets on CVP {{inventory_hostname}}.'
      tags:
        - deprovision
      arista.cvp.cv_configlet_v3:
        configlets: "{{configlet_list}}"
        configlets_notes: "Configlet managed by Ansible"
        state: absent
      register: cvp_configlet
